export const BATCH_ACTION_TYPES = {
    SET_BATCH_FORM_DATA: "SET_BATCH_FORM_DATA",
    SET_TOTAL_RATING_CHANGE: "SET_TOTAL_RATING_CHANGE",
    RESET_ALL_RATING_CHANGES: "RESET_ALL_RATING_CHANGES",
    SET_GAME_DATA: "SET_GAME_DATA",
    ADD_GAME: "ADD_GAME",
    REMOVE_GAME: "REMOVE_GAME"
}